[versions]
agp = "8.6.1"
kotlin = "1.9.0"

junit = "4.13.2"
junitVersion = "1.2.1"
coreKtx = "1.15.0"

androidxmaterial = "1.12.0"

matecom = "1.7.8"

googleServiceVersion = "4.4.2"
appCompats = "1.7.0"
databaseReal="21.0.0"
messagingReal="24.1.0"
espressoCore = "3.6.1"

[libraries]
# Material Design Components
androidxmaterial = { group = "com.google.android.material", name = "material", version.ref = "androidxmaterial" }


# Jetpack Compose Material
matecom = { group = "androidx.compose.material", name = "material", version.ref = "matecom" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" } # JUnit 4
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" } # AndroidX JUnit
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" } # Espresso Core

# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" } # Core KTX

# AppCompat
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompats" } # AppCompat

# Firebase
database = { group = "com.google.firebase", name = "firebase-database", version.ref = "databaseReal" } # Firebase Realtime Database
messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "messagingReal" } # Firebase Cloud Messaging


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleService={id ="com.google.gms.google-services", version.ref = "googleServiceVersion"}
